-- MEGA UPDATE SCRIPT: Run this entire file in Supabase SQL Editor

-- 1. Enable UUID extension
create extension if not exists "uuid-ossp";

-- 2. UPDATE USERS TABLE
-- Add missing columns for profile
alter table public.users add column if not exists skills text[];
alter table public.users add column if not exists social_links jsonb default '{}'::jsonb;
alter table public.users add column if not exists website_url text;
alter table public.users add column if not exists github_url text;
alter table public.users add column if not exists linkedin_url text;
alter table public.users add column if not exists bio text;
alter table public.users add column if not exists phone text;
alter table public.users add column if not exists avatar_url text;

-- 3. CREATE/UPDATE USER_STATS
create table if not exists public.user_stats (
    user_id uuid references auth.users(id) on delete cascade primary key,
    problems_solved int default 0,
    current_streak int default 0,
    last_activity_date date,
    total_xp int default 0,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. ADDITIONAL TABLES FOR PROFILE
-- Achievements & Activity
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  title text not null unique,
  description text,
  icon_name text, 
  condition_type text not null, 
  xp_reward int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  achievement_id bigint references achievements(id) on delete cascade not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, achievement_id)
);

create table if not exists public.user_activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  activity_type text not null, 
  activity_date date default current_date not null,
  count int default 1
);

-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- Users Table
alter table public.users enable row level security;
drop policy if exists "Public profiles are viewable by everyone" on public.users;
create policy "Public profiles are viewable by everyone" on public.users for select using (true);

drop policy if exists "Users can update their own profile" on public.users;
create policy "Users can update their own profile" on public.users for update using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.users;
create policy "Users can insert their own profile" on public.users for insert with check (auth.uid() = id);

-- User Stats
alter table public.user_stats enable row level security;
drop policy if exists "Everyone can view stats" on user_stats;
create policy "Everyone can view stats" on user_stats for select using (true);

drop policy if exists "Users can update own stats" on user_stats;
create policy "Users can update own stats" on user_stats for update using (auth.uid() = user_id);

drop policy if exists "Users can insert own stats" on user_stats;
create policy "Users can insert own stats" on user_stats for insert with check (auth.uid() = user_id);

-- Achievements & Activity
alter table public.user_achievements enable row level security;
drop policy if exists "Public user achievements" on user_achievements;
create policy "Public user achievements" on user_achievements for select using (true);

alter table public.user_activity_log enable row level security;
drop policy if exists "Public user activity" on user_activity_log;
create policy "Public user activity" on user_activity_log for select using (true);

-- 6. TRIGGERS
-- Ensure user_stats exists when a user is created
create or replace function public.handle_new_user_stats()
returns trigger as $$
begin
  insert into public.user_stats (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger on public.users (primary user data table)
drop trigger if exists on_public_user_stats_check on public.users;
create trigger on_public_user_stats_check
after insert on public.users
for each row execute procedure public.handle_new_user_stats();


-- 7. STORAGE FOR AVATARS
insert into storage.buckets (id, name, public) 
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

create policy "Avatar images are publicly accessible"
on storage.objects for select
using ( bucket_id = 'avatars' );

create policy "Anyone can upload an avatar"
on storage.objects for insert
with check ( bucket_id = 'avatars' AND auth.role() = 'authenticated' );

create policy "Anyone can update their own avatar"
on storage.objects for update
using ( bucket_id = 'avatars' AND auth.uid() = owner )
with check ( bucket_id = 'avatars' AND auth.uid() = owner );

-- 8. DEFAULT DATA
insert into achievements (title, description, condition_type, xp_reward, icon_name)
values 
('First login', 'Logged in for the first time', 'login', 10, 'user'),
('Profile Completed', 'Filled out profile details', 'profile', 50, 'edit')
on conflict (title) do nothing;
