-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- 1. COMMUNITY FEATURES
-- Discussions Table
create table if not exists discussions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null,
  content text not null, -- Markdown content
  topic text not null, -- e.g., 'Arrays', 'DP', 'General'
  category text default 'general', -- 'doubt', 'discussion', 'announcement'
  upvotes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Replies Table
create table if not exists discussion_replies (
  id bigint generated by default as identity primary key,
  discussion_id bigint references discussions(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  content text not null, 
  upvotes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Votes Table (to track who voted on what, preventing multiple votes)
create table if not exists discussion_votes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  item_id bigint not null,
  item_type text not null check (item_type in ('discussion', 'reply')),
  vote_type int not null check (vote_type in (1, -1)), -- 1 for upvote, -1 for downvote
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, item_id, item_type)
);

-- Reports Table
create table if not exists reports (
  id bigint generated by default as identity primary key,
  reported_by uuid references auth.users(id) not null,
  resource_id bigint not null,
  resource_type text not null check (resource_type in ('discussion', 'reply')),
  reason text not null,
  status text default 'pending' check (status in ('pending', 'reviewed', 'resolved')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. CERTIFICATES
-- Update certificates table to include unique_code for sharing
alter table certificates add column if not exists unique_code uuid default uuid_generate_v4() unique;
-- Add user_name snapshot for the certificate (in case they change it later)
alter table certificates add column if not exists user_name text;

-- 3. ACHIEVEMENTS
-- Ensure achievements table exists (already in supabase.ts types, making sure it's in DB)
create table if not exists achievements (
  id bigint generated by default as identity primary key,
  title text not null unique,
  description text,
  icon_name text, -- e.g., 'star', 'trophy'
  condition_type text not null, -- e.g., 'first_solve', 'streak_7', 'master'
  xp_reward int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- User Achievements (Unlocks)
create table if not exists user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  achievement_id bigint references achievements(id) on delete cascade not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, achievement_id)
);

-- 4. USER STREAKS & STATS
create table if not exists user_stats (
  user_id uuid references auth.users(id) on delete cascade primary key,
  problems_solved int default 0,
  current_streak int default 0,
  last_activity_date date,
  total_xp int default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES (Basic examples, refine as needed)
alter table discussions enable row level security;
alter table discussion_replies enable row level security;
alter table discussion_votes enable row level security;
alter table user_achievements enable row level security;
alter table user_stats enable row level security;

-- Allow everyone to read discussions
create policy "Public discussions are viewable by everyone" on discussions for select using (true);
-- Allow authenticated users to insert discussions
create policy "Authenticated users can create discussions" on discussions for insert with check (auth.role() = 'authenticated');
-- Allow users to update their own discussions
create policy "Users can update own discussions" on discussions for update using (auth.uid() = user_id);

-- Similar for replies
create policy "Public replies are viewable by everyone" on discussion_replies for select using (true);
create policy "Authenticated users can reply" on discussion_replies for insert with check (auth.role() = 'authenticated');

-- Stats policies
create policy "Users can view own stats" on user_stats for select using (auth.uid() = user_id);
create policy "Service role to update stats" on user_stats for all using (true); -- Ideally handle updates via server functions or triggers

-- INSERT DEFAULT ACHIEVEMENTS
insert into achievements (title, description, condition_type, xp_reward, icon_name)
values 
('First Problem Solved', 'Congratulations on solving your first DSA problem!', 'first_solve', 100, 'trophy'),
('7-Day Streak', 'You have been consistent for 7 days!', 'streak_7', 500, 'fire'),
('DSA Master', 'Solved 100 Hard problems', 'dsa_master', 5000, 'crown')
on conflict (title) do nothing;

-- 5. ALGORITHM COMPARISON MODULE
create table if not exists algorithm_metadata (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  complexity_time_best text,
  complexity_time_average text,
  complexity_time_worst text,
  complexity_space text,
  use_cases text[],
  pseudocode text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. MISTAKE ANALYZER MODULE
create table if not exists mistake_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  problem_title text,
  submission_code text,
  mistake_pattern text, -- e.g., 'Off-by-one', 'Logic Error'
  feedback text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for new tables
alter table algorithm_metadata enable row level security;
alter table mistake_history enable row level security;

create policy "Public algorithms are viewable by everyone" on algorithm_metadata for select using (true);
create policy "Users can view own mistakes" on mistake_history for select using (auth.uid() = user_id);
create policy "Authenticated users can insert mistakes" on mistake_history for insert with check (auth.role() = 'authenticated');

-- SEED DATA FOR ALGORITHMS
insert into algorithm_metadata (name, slug, description, complexity_time_best, complexity_time_average, complexity_time_worst, complexity_space, use_cases, pseudocode)
values 
('Bubble Sort', 'bubble-sort', 'Simple sorting algorithm that repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order.', 'O(n)', 'O(n²)', 'O(n²)', 'O(1)', ARRAY['Educational purposes', 'Small datasets'], 'procedure bubbleSort(A : list of sortable items)
    n = length(A)
    repeat
        swapped = false
        for i = 1 to n-1 inclusive do
            if A[i-1] > A[i] then
                swap(A[i-1], A[i])
                swapped = true
            end if
        end for
        n = n - 1
    until not swapped
end procedure'),
('Quick Sort', 'quick-sort', 'Efficient, in-place sorting algorithm that uses a divide-and-conquer strategy.', 'O(n log n)', 'O(n log n)', 'O(n²)', 'O(log n)', ARRAY['Large datasets', 'General purpose sorting'], 'algorithm quicksort(A, lo, hi) is
    if lo < hi then
        p := partition(A, lo, hi)
        quicksort(A, lo, p - 1)
        quicksort(A, p + 1, hi)
    end if
end algorithm'),
('Merge Sort', 'merge-sort', 'Divide and conquer algorithm that divides the input array into two halves, calls itself for the two halves, and then merges the two sorted halves.', 'O(n log n)', 'O(n log n)', 'O(n log n)', 'O(n)', ARRAY['Linked Lists', 'Stable sort requirements'], 'function merge_sort(list m) is
    if length of m <= 1 then
        return m
    var left := empty list
    var right := empty list
    for each x with index i in m do
        if i < (length of m)/2 then
            add x to left
        else
            add x to right
    left := merge_sort(left)
    right := merge_sort(right)
    return merge(left, right)
end function')

-- 7. EXAM MODE RESOURCES
create table if not exists exam_resources (
  id bigint generated by default as identity primary key,
  subject_code text not null, -- e.g., 'CE301' linked to subjects
  title text not null,
  content text,
  resource_type text check (resource_type in ('note', 'question', 'pyq')),
  marks int,
  is_important boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. SUBJECT DEPENDENCIES
create table if not exists subject_dependencies (
  id bigint generated by default as identity primary key,
  subject_code text not null,
  prerequisite_code text not null,
  unique(subject_code, prerequisite_code)
);

-- RLS
alter table exam_resources enable row level security;
alter table subject_dependencies enable row level security;

create policy "Public exam resources" on exam_resources for select using (true);
create policy "Public dependencies" on subject_dependencies for select using (true);

-- SEED DATA
insert into exam_resources (subject_code, title, content, resource_type, marks, is_important)
values 
('CE301', 'Von Neumann Architecture', 'Explain the stored program concept and bottleneck.', 'question', 5, true),
('CE301', 'Cache Memory Mapping', 'Direct, Associative, and Set Associative Mapping techniques.', 'note', null, true),
('CE301', 'Pipeline Hazards', 'What are data, structural, and control hazards?', 'question', 10, true),
('CE302', '3rd Normal Form', 'Define 3NF and give an example.', 'question', 5, true),
('CE302', 'ACID Properties', 'Explain Atomicity, Consistency, Isolation, Durability.', 'note', null, true),
('CE303', 'TCP vs UDP', 'Differentiate between TCP and UDP headers.', 'question', 5, false),
('CE304', 'Deadlock Conditions', 'Explain mutual exclusion, hold and wait, no preemption, circular wait.', 'question', 10, true);

insert into subject_dependencies (subject_code, prerequisite_code)
values
('CE304', 'CE301'), -- OS needs COA
('CE302', 'CE306'), -- DBMS (relational algebra) needs Theory of Computation (logic) - loosely
('CE303', 'CE304'); -- Networks needs OS concepts


-- 9. ADAPTIVE DIFFCULTY ENGINE
create table if not exists user_performance_metrics (
  user_id uuid references auth.users(id) on delete cascade primary key,
  current_rating int default 1000,
  average_accuracy float default 0, -- 0 to 1
  average_speed_ms int default 0,
  problems_attempted int default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. TIMED CONTESTS
create table if not exists contests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  status text check (status in ('upcoming', 'active', 'ended')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists contest_problems (
  contest_id bigint references contests(id) on delete cascade,
  problem_id int, -- references dsa_problems(id) roughly
  points int default 100,
  primary key (contest_id, problem_id)
);

create table if not exists contest_submissions (
  id bigint generated by default as identity primary key,
  contest_id bigint references contests(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  problem_id int not null,
  submission_code text,
  language text default 'python',
  status text, -- 'Accepted', 'Wrong Answer'
  execution_time_ms int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table user_performance_metrics enable row level security;
alter table contests enable row level security;
alter table contest_problems enable row level security;
alter table contest_submissions enable row level security;

create policy "Users view own performance" on user_performance_metrics for select using (auth.uid() = user_id);
create policy "Services update performance" on user_performance_metrics for all using (true);

create policy "Public contests" on contests for select using (true);
create policy "Public contest problems" on contest_problems for select using (true);

create policy "Users see own submissions" on contest_submissions for select using (auth.uid() = user_id);
create policy "Users submit during contest" on contest_submissions for insert with check (auth.role() = 'authenticated');

-- SEED CONTESTS
insert into contests (title, description, start_time, end_time, status)
values
('Weekly Bi-Wizard Contest 1', 'Test your arrays and strings knowledge.', now() + interval '2 days', now() + interval '2 days 2 hours', 'upcoming'),
('Dynamic Programming Sprint', 'Speed contest for DP problems.', now() - interval '1 day', now() - interval '22 hours', 'ended'),
('Grandmaster Challenge', 'Hardest problems from the archive.', now(), now() + interval '3 hours', 'active');

-- 11. DASHBOARD ACTIVITY & CAREER SCORE
create table if not exists user_activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  activity_type text not null, -- 'problem_solve', 'video_watch', 'discussion_post'
  activity_date date default current_date not null,
  count int default 1
);

-- Career score cache (optional, but good for performance)
create table if not exists career_readiness_scores (
  user_id uuid references auth.users(id) on delete cascade primary key,
  score int default 0,
  dsa_split int default 0,
  dev_split int default 0,
  cs_fundamentals_split int default 0,
  consistency_bonus int default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 12. MENTOR CONNECT
create table if not exists mentors (
  user_id uuid references auth.users(id) on delete cascade primary key,
  headline text,
  bio text,
  skills text[],
  hourly_rate int default 0,
  is_verified boolean default false,
  available_slots jsonb default '[]'::jsonb
);

create table if not exists mentor_bookings (
  id bigint generated by default as identity primary key,
  mentor_id uuid references mentors(user_id) on delete cascade not null,
  mentee_id uuid references auth.users(id) on delete cascade not null,
  status text default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  scheduled_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 13. ANSWER VERIFICATION
alter table discussion_replies add column if not exists is_verified boolean default false;
alter table discussion_replies add column if not exists verified_by uuid references auth.users(id);

-- 14. SKILL TREE
create table if not exists skill_nodes (
  id text primary key, -- e.g., 'arrays-101'
  label text not null,
  category text, -- 'dsa', 'web', 'core'
  parent_id text references skill_nodes(id),
  position_x int default 0,
  position_y int default 0
);

create table if not exists user_unlocked_skills (
  user_id uuid references auth.users(id) on delete cascade not null,
  skill_id text references skill_nodes(id) on delete cascade not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, skill_id)
);

-- RLS
alter table user_activity_log enable row level security;
alter table career_readiness_scores enable row level security;
alter table mentors enable row level security;
alter table mentor_bookings enable row level security;
alter table skill_nodes enable row level security;
alter table user_unlocked_skills enable row level security;

create policy "Users view own activity" on user_activity_log for select using (auth.uid() = user_id);
create policy "Users view public mentors" on mentors for select using (true);
create policy "Users manage own bookings" on mentor_bookings for all using (auth.uid() = mentee_id or auth.uid() = mentor_id);
create policy "Skill nodes visible to all" on skill_nodes for select using (true);
create policy "User skills visible to self" on user_unlocked_skills for select using (auth.uid() = user_id);

-- SEED SKILL NODES
insert into skill_nodes (id, label, category, parent_id, position_x, position_y)
values
('root', 'Computer Science', 'core', null, 0, 0),
('dsa', 'Data Structures', 'dsa', 'root', -100, 100),
('web', 'Web Development', 'web', 'root', 100, 100),
('arrays', 'Arrays', 'dsa', 'dsa', -150, 200),
('ll', 'Linked Lists', 'dsa', 'dsa', -50, 200),
('react', 'React.js', 'web', 'web', 50, 200),
('db', 'Databases', 'web', 'web', 150, 200)
on conflict (id) do nothing;
